# Generated by Django 5.2.16 on 2026-07-19 12:03

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sig_app', '0002_commune_departement_region_delete_point_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Raster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('raster', django.contrib.gis.db.models.fields.RasterField(srid=32628)),
            ],
        ),
    ]
