# Generated by Django 5.2.16 on 2026-07-19 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sig_app', '0003_raster'),
    ]

    operations = [
        migrations.RenameField(
            model_name='raster',
            old_name='raster',
            new_name='rst',
        ),
    ]
