# Generated by Django 5.2.16 on 2026-07-19 12:13

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sig_app', '0004_rename_raster_raster_rst'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raster',
            name='rst',
            field=django.contrib.gis.db.models.fields.RasterField(srid=4326),
        ),
    ]
